# Theme metadata
name = "arme_theme"

[light]
  # Primary
  primary = "#a2a2a2"

  # Menu
  menu_primary = "#fff"
  menu_text = "#34495e"
  menu_text_active = "#848a9b"
  menu_title = "#2b2b2b"

  # Home sections
  home_section_odd = "rgb(255, 255, 255)"
  home_section_even = "rgb(247, 247, 247)"

[dark]
  # Primary
  primary = "#bbdefb"

  link = "#bbdefb"
  link_hover = "#bbdefb"
