# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  identifier = "team"
  name = "Team"
  url = "team"
  weight = 30

[[main]]
  identifier = "outcomes"
  name = "Outcomes"
  url = "outcomes"
  weight = 20

[[main]]
  identifier = "internal"
  name = "Internal"
  url = "/internal"
  weight = 90
  [[main]]
    identifier = "Sharepoint"
    name = "Sharepoint"
    url = "https://bham.sharepoint.com/sites/AugmentedRealityMusicEnsemble-Project"
    parent = "internal"
    weight = 1
  [[main]]
    identifier = "Coda"
    name = "Coda"
    url = "https://tinyurl.com/CODAVRLab"
    parent = "internal"
    weight = 2
     [[main]]
    identifier = "RDS"
    name = "RDS"
    url = "https://portal.bear.bham.ac.uk/pun/sys/files/fs/rds/projects/d/dilucam-arme/"
    parent = "internal"
    weight = 3
   
   [[main]]
    identifier = "Site Maintenance"
    name = "Site Maintenance"
    url = "site_maintenance"
    parent = "internal"
    weight = 4
    

    
    
#   [[main]]
#     name = "Twitter"
#     url = "twitter"
#     weight = 70

[[main]]
  name = "Contact"
  url = "contact"
  weight = 80
