# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
  identifier = "team"
  name = "Team"
  url = "team"
  weight = 30

[[main]]
  identifier = "outcomes"
  name = "Outcomes"
  url = "outcomes"
  weight = 20

#   [[main]]
#     name = "Twitter"
#     url = "twitter"
#     weight = 70

[[main]]
  name = "Contact"
  url = "contact"
  weight = 80

[[footer_internal]]
  identifier = "Sharepoint"
  name = "Sharepoint"
  url = "https://bham.sharepoint.com/sites/AugmentedRealityMusicEnsemble-Project"
  weight = 1

[[footer_internal]]
  identifier = "Coda"
  name = "Coda"
  url = "https://tinyurl.com/CODAVRLab"
  weight = 2

[[footer_internal]]
  identifier = "RDS"
  name = "RDS"
  url = "https://portal.bear.bham.ac.uk/pun/sys/files/fs/rds/projects/d/dilucam-arme/"
  weight = 3

[[footer_internal]]
  identifier = "Site Maintenance"
  name = "Site Maintenance"
  url = "site_maintenance"
  weight = 4
