# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "/"
#  weight = 10

[[main]]
name = "News"
url = "post"
weight = 20


[[main]]
    identifier = "team"
    name = "Team"
    url = "/team"
    weight = 30
    
    
    
    [[main]]
    identifier = "Consortium"
    name = "Consortium"
    url = "partners"
    parent = "team"
    weight = 1
  [[main]]
    identifier = "People"
    name = "People"
    url = "people"
    parent = "team"
    weight = 2
    
  
  
  
[[main]]
    identifier = "output"
    name = "Outcomes"
    url = "/output"
    weight = 30

[[main]]
   identifier = "Publications"
    name = "Publications"
  url = "publication"
  parent = "output"
   weight = 1
  

[[main]]
   identifier = "Demos"
    name = "Demos"
  url = "demos"
  parent = "output"
   weight = 2


[[main]]
   identifier = "Researchfish"
    name = "Researchfish"
  url ="https://app.researchfish.com/awards/viewdetails/0?gorderby=organisation&filter=89804838_5f3e28d9cd2e26_AW"
  parent = "output"
   weight = 3


[[main]]
    identifier = "internal"
    name = "Internal"
    url = "/internal"
    weight = 61
  [[main]]
    identifier = "Sharepoint"
    name = "Sharepoint"
    url = "https://bham.sharepoint.com/sites/AugmentedRealityMusicEnsemble-Project"
    parent = "internal"
    weight = 1
  [[main]]
    identifier = "Coda"
    name = "Coda"
    url = "https://tinyurl.com/CODAVRLab"
    parent = "internal"
    weight = 2
     [[main]]
    identifier = "BEAR"
    name = "BEAR"
    url = "    https://bearadmin.bham.ac.uk/identity/project/dilucam-arme"
    parent = "internal"
    weight = 3

    
    
    
#   [[main]]
#     name = "Twitter"
#     url = "twitter"
#     weight = 70

[[main]]
  name = "Contact"
  url = "contact"
  weight = 80
